/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiểm tra kết nối DB, Redis, engine */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm địa điểm (MOCK — danh sách cố định, xem README) */
        get: operations["Maps_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng ký tài khoản hành khách hoặc tài xế */
        post: operations["Auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng email + mật khẩu, trả về JWT */
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin người dùng hiện tại */
        get: operations["Auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách xe của tài xế đang đăng nhập */
        get: operations["Vehicles_list"];
        put?: never;
        /** Thêm xe */
        post: operations["Vehicles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật xe / ngừng sử dụng (isActive=false) */
        patch: operations["Vehicles_update"];
        trace?: never;
    };
    "/trips/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm chuyến phù hợp theo điểm đón/trả, ngày giờ, số ghế (công khai) */
        get: operations["Trips_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Các chuyến của tài xế đang đăng nhập */
        get: operations["Trips_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết chuyến (công khai, ẩn SĐT tài xế) */
        get: operations["Trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tài xế sửa giá (khi chưa có khách) hoặc ghi chú */
        patch: operations["Trips_update"];
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tài xế đăng chuyến mới */
        post: operations["Trips_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tài xế cập nhật trạng thái chuyến */
        patch: operations["Trips_changeStatus"];
        trace?: never;
    };
    "/trips/{id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách khách của chuyến (kèm SĐT) — chỉ tài xế của chuyến */
        get: operations["Trips_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hành khách đặt ghế */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử đặt chỗ của hành khách */
        get: operations["Bookings_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hành khách hủy vé */
        post: operations["Bookings_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tài xế từ chối khách */
        post: operations["Bookings_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Số liệu tổng quan */
        get: operations["Admin_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách người dùng */
        get: operations["Admin_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Khóa / mở khóa người dùng */
        patch: operations["Admin_updateUserStatus"];
        trace?: never;
    };
    "/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tài xế (lọc theo trạng thái duyệt) */
        get: operations["Admin_drivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duyệt tài xế */
        post: operations["Admin_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/drivers/{userId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Từ chối tài xế */
        post: operations["Admin_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách chuyến */
        get: operations["Admin_trips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/trips/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hủy chuyến (hủy luôn các vé đang hiệu lực) */
        post: operations["Admin_cancelTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @enum {string} */
            status: "ok" | "degraded";
            database: boolean;
            redis: boolean;
            engine: boolean;
        };
        PlaceDto: {
            id: string;
            /** @description Tên ngắn, ví dụ "Bến xe Mỹ Đình" */
            name: string;
            /** @description Địa chỉ đầy đủ để hiển thị */
            address: string;
            /** @description Tỉnh / thành phố */
            province: string;
            lat: number;
            lng: number;
        };
        RegisterDto: {
            /**
             * @description Chỉ cho phép tự đăng ký PASSENGER hoặc DRIVER. ADMIN được tạo qua seed/CLI.
             * @enum {string}
             */
            role: "PASSENGER" | "DRIVER";
            /** Format: email */
            email: string;
            /** @description Số điện thoại Việt Nam, ví dụ 0912345678 */
            phone: string;
            password: string;
            fullName: string;
            /** @description Số giấy phép lái xe — bắt buộc khi role = DRIVER */
            licenseNumber?: string;
        };
        /** @enum {string} */
        Role: "PASSENGER" | "DRIVER" | "ADMIN";
        /** @enum {string} */
        UserStatus: "ACTIVE" | "LOCKED";
        /** @enum {string} */
        DriverStatus: "PENDING" | "APPROVED" | "REJECTED";
        DriverProfileDto: {
            status: components["schemas"]["DriverStatus"];
            id: string;
            licenseNumber: string;
            rejectReason?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UserDto: {
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            id: string;
            email: string;
            phone: string;
            fullName: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Chỉ có với tài xế */
            driverProfile?: components["schemas"]["DriverProfileDto"] | null;
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @enum {string} */
        VehicleType: "SEATS_5" | "SEATS_7";
        VehicleDto: {
            type: components["schemas"]["VehicleType"];
            id: string;
            plateNumber: string;
            brand: string;
            model: string;
            color?: string | null;
            /** @description Số ghế hành khách tối đa (4 hoặc 6) */
            passengerCapacity: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateVehicleDto: {
            /** @description SEATS_5 (tối đa 4 khách) hoặc SEATS_7 (tối đa 6 khách) */
            type: components["schemas"]["VehicleType"];
            /** @description Biển số, ví dụ 30A-123.45 */
            plateNumber: string;
            brand: string;
            model: string;
            color?: string;
        };
        UpdateVehicleDto: {
            /** @description SEATS_5 (tối đa 4 khách) hoặc SEATS_7 (tối đa 6 khách) */
            type?: components["schemas"]["VehicleType"];
            /** @description Biển số, ví dụ 30A-123.45 */
            plateNumber?: string;
            brand?: string;
            model?: string;
            color?: string;
            isActive?: boolean;
        };
        /** @enum {string} */
        TripStatus: "SCHEDULED" | "ONGOING" | "COMPLETED" | "CANCELLED";
        MatchInfoDto: {
            /** @description Điểm phù hợp 0–100 (cao hơn là tốt hơn) */
            score: number;
            /** @description Khoảng cách từ điểm đón tới tuyến đường của chuyến (km) */
            pickupDistanceKm: number;
            /** @description Khoảng cách từ điểm trả tới tuyến đường của chuyến (km) */
            dropoffDistanceKm: number;
            /** @description Quãng đường tài xế phải đi thêm để đón/trả (km, ước lượng) */
            detourKm: number;
            /** @description Lệch so với giờ mong muốn (phút, dương = chuyến đi muộn hơn) */
            timeDiffMinutes?: number | null;
            reasons: string[];
        };
        LocationDto: {
            address: string;
            lat: number;
            lng: number;
        };
        UserSummaryDto: {
            id: string;
            fullName: string;
            /** @description Chỉ trả về khi người xem có quyền (vd: tài xế xem khách đã đặt, khách xem tài xế của chuyến đã đặt) */
            phone?: string;
        };
        TripMatchDto: {
            status: components["schemas"]["TripStatus"];
            match: components["schemas"]["MatchInfoDto"];
            id: string;
            origin: components["schemas"]["LocationDto"];
            destination: components["schemas"]["LocationDto"];
            /** Format: date-time */
            departureTime: string;
            /** @description VND */
            pricePerSeat: number;
            totalSeats: number;
            availableSeats: number;
            note?: string | null;
            driver: components["schemas"]["UserSummaryDto"];
            vehicle: components["schemas"]["VehicleDto"];
            /** @description Số ghế đã được đặt = totalSeats - availableSeats */
            bookedSeats: number;
            /** Format: date-time */
            createdAt: string;
        };
        SearchTripsResponseDto: {
            /**
             * @description engine = do matching engine xếp hạng; fallback = engine lỗi, dùng xếp hạng dự phòng
             * @enum {string}
             */
            matchSource: "engine" | "fallback";
            items: components["schemas"]["TripMatchDto"][];
            /** @description Tên maps provider đang dùng ("mock" ở giai đoạn đầu) */
            mapsProvider: string;
        };
        TripDto: {
            status: components["schemas"]["TripStatus"];
            id: string;
            origin: components["schemas"]["LocationDto"];
            destination: components["schemas"]["LocationDto"];
            /** Format: date-time */
            departureTime: string;
            /** @description VND */
            pricePerSeat: number;
            totalSeats: number;
            availableSeats: number;
            note?: string | null;
            driver: components["schemas"]["UserSummaryDto"];
            vehicle: components["schemas"]["VehicleDto"];
            /** @description Số ghế đã được đặt = totalSeats - availableSeats */
            bookedSeats: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateTripDto: {
            /** Format: uuid */
            vehicleId: string;
            origin: components["schemas"]["LocationDto"];
            destination: components["schemas"]["LocationDto"];
            /** @description Giờ khởi hành (ISO 8601, có múi giờ, ví dụ 2026-10-01T07:30:00+07:00) */
            departureTime: string;
            /** @description Giá mỗi ghế (VND), bội số của 1.000 */
            pricePerSeat: number;
            /** @description Số ghế mở bán (xe 5 chỗ ≤ 4, xe 7 chỗ ≤ 6) */
            totalSeats: number;
            note?: string;
        };
        UpdateTripDto: {
            /** @description Chỉ đổi được khi chuyến chưa có khách đặt */
            pricePerSeat?: number;
            note?: string;
        };
        UpdateTripStatusDto: {
            /**
             * @description SCHEDULED → ONGOING → COMPLETED; hoặc hủy (CANCELLED) khi chưa hoàn thành
             * @enum {string}
             */
            status: "ONGOING" | "COMPLETED" | "CANCELLED";
            reason?: string;
        };
        /** @enum {string} */
        BookingStatus: "CONFIRMED" | "CANCELLED" | "REJECTED" | "COMPLETED";
        BookingDto: {
            status: components["schemas"]["BookingStatus"];
            id: string;
            tripId: string;
            seats: number;
            /** @description Đơn giá tại thời điểm đặt (VND) */
            pricePerSeat: number;
            /** @description Tổng tiền (VND) = seats × pricePerSeat, do backend tính */
            totalPrice: number;
            pickup: components["schemas"]["LocationDto"];
            dropoff: components["schemas"]["LocationDto"];
            note?: string | null;
            cancelReason?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Có khi tài xế/admin xem */
            passenger?: components["schemas"]["UserSummaryDto"];
            /** @description Có khi hành khách xem lịch sử */
            trip?: components["schemas"]["TripDto"];
        };
        CreateBookingDto: {
            /** Format: uuid */
            tripId: string;
            /** @description Số ghế muốn đặt */
            seats: number;
            /** @description Điểm đón của hành khách (nằm trên/gần tuyến) */
            pickup: components["schemas"]["LocationDto"];
            /** @description Điểm trả của hành khách */
            dropoff: components["schemas"]["LocationDto"];
            note?: string;
        };
        CancelBookingDto: {
            reason?: string;
        };
        AdminStatsDto: {
            totalUsers: number;
            totalPassengers: number;
            totalDrivers: number;
            pendingDrivers: number;
            scheduledTrips: number;
            confirmedBookings: number;
        };
        AdminUserDto: {
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            id: string;
            email: string;
            phone: string;
            fullName: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Chỉ có với tài xế */
            driverProfile?: components["schemas"]["DriverProfileDto"] | null;
            vehicleCount: number;
        };
        PaginatedUsersDto: {
            items: components["schemas"]["AdminUserDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        UpdateUserStatusDto: {
            status: components["schemas"]["UserStatus"];
        };
        ReviewDriverDto: {
            /** @description Lý do (bắt buộc khi từ chối) */
            reason?: string;
        };
        PaginatedTripsDto: {
            items: components["schemas"]["TripDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        AdminCancelTripDto: {
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    Maps_search: {
        parameters: {
            query?: {
                /** @description Từ khóa (không phân biệt dấu). Bỏ trống để lấy danh sách gợi ý. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"][];
                };
            };
        };
    };
    Auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    Auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    Vehicles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"][];
                };
            };
        };
    };
    Vehicles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
        };
    };
    Vehicles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDto"];
                };
            };
        };
    };
    Trips_search: {
        parameters: {
            query: {
                pickupLat: number;
                pickupLng: number;
                dropoffLat: number;
                dropoffLng: number;
                /** @description Ngày đi theo giờ Việt Nam (YYYY-MM-DD) */
                date: string;
                /** @description Giờ mong muốn theo giờ Việt Nam (HH:mm). Bỏ trống = cả ngày */
                time?: string;
                seats: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTripsResponseDto"];
                };
            };
        };
    };
    Trips_mine: {
        parameters: {
            query?: {
                status?: components["schemas"]["TripStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"][];
                };
            };
        };
    };
    Trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    Trips_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    Trips_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    Trips_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    Trips_bookings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
        };
    };
    Bookings_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"][];
                };
            };
        };
    };
    Bookings_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelBookingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
        };
    };
    Bookings_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelBookingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDto"];
                };
            };
        };
    };
    Admin_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsDto"];
                };
            };
        };
    };
    Admin_users: {
        parameters: {
            query?: {
                role?: components["schemas"]["Role"];
                status?: components["schemas"]["UserStatus"];
                /** @description Tìm theo tên, email hoặc SĐT */
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsersDto"];
                };
            };
        };
    };
    Admin_updateUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
        };
    };
    Admin_drivers: {
        parameters: {
            query?: {
                status?: components["schemas"]["DriverStatus"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsersDto"];
                };
            };
        };
    };
    Admin_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDriverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
        };
    };
    Admin_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDriverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
        };
    };
    Admin_trips: {
        parameters: {
            query?: {
                status?: components["schemas"]["TripStatus"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTripsDto"];
                };
            };
        };
    };
    Admin_cancelTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCancelTripDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
}
